version: "3.7"
services:
  web:
    build: 
      context: ./
    environment:
      - PORT=3000
    ports:
      - "3000:3000"
    volumes:
      - ./:/web
      - /web/node_modules
    command: ["npm", "run", "start"]